### ISSUE TITLE
Filter out pull requests from output?

### ISSUE THREAD

**Issue by Pustur** [mjswensen/shoulders#12]
Since `shoulders` is meant to show the open issues for the packages we use, I find it a bit annoying that pull requests show up as well.

The github API treats them like issues, but we could filter them out by looking if the `pull_request` key is present as documented [here](https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#article-contents).

What do you think? Should we filter out the PRs? If so should that be the default behavior or should it be behind a flag?

I would be interested in implementing this feature should you decide it's something you want to add.

**Comment by mjswensen** [comment]
Great point, @Pustur , this is a silly oversight on my part. I forgot that GitHub groups PRs in with issues. Yes, I think they should be excluded from the output and probably there's no need to even include them behind a flag. Feel free to work on the implementation, that would be great!
