### ISSUE TITLE
Feature Request/Implementation: output to HTML/MD file

### ISSUE THREAD

**Issue by chrispinkney** [mjswensen/shoulders#5]
Hey!

(full disclosure) I discovered your project through my college professor @humphd and think it's a wonderful idea! I'd like to contribute to it if possible.

I'd like to add the ability to specify `--tofile` at runtime which will dump the console results to an HTML/MD file for easier reading ability. I mean no offence by this feature and just wanted to try my hand at adding something that might be of value to your project!

I've actually already implemented a working demo and with your permission I'll submit a PR for your review.

Introduced in #8 

Thanks and let me know :smile:
-Chris

**Comment by mjswensen** [comment]
Hello, @chrispinkney ! Thank you so much for taking the time to write up this feature request AND implement a solution! I really like this feature idea a lot. Let's take the discussion over to #8 for next steps.

**Comment by mjswensen** [comment]
Closed via #8 .
