### ISSUE TITLE
Missing `g` flag in regex for labels option

### ISSUE THREAD

**Issue by Pustur** [mjswensen/shoulders#7]
This regex is missing a `g` (global) flag.  
As it is now it will only replace the first occurrence it finds.

https://github.com/mjswensen/shoulders/blob/fa665f78f0d1c66db72ce3dd026d866268551adc/index.js#L26

Introduced in #2

**Comment by Kardelio** [comment]
If its ok ill quickly knock this one out the park #OneCharacterChange <3 PR incoming...

**Comment by mjswensen** [comment]
Closed via #9
